/*
 * storage open api
 *
 * storage open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage-api-go
// QCloudCredentialsData 腾讯云上传凭证数据
type QCloudCredentialsData struct {
	// 请求时需要用的 token 字符串，最终请求 COS API 时，需要放在 Header 的 x-cos-security-token 字段
	SessionToken string `json:"sessionToken"`
	// 临时密钥 Id，可用于计算签名
	TmpSecretId string `json:"tmpSecretId"`
	// 临时密钥 Key，可用于计算签名
	TmpSecretKey string `json:"tmpSecretKey"`
	// 密钥的起始时间戳（毫秒）
	StartTime int64 `json:"startTime"`
	// 密钥的失效时间戳（毫秒）
	ExpiredTime int64 `json:"expiredTime"`
	// 请求ID
	RequestId string `json:"requestId"`
}
