/*
 * Storage open api
 *
 * storage open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage
// CreateUploadCredentialsReq struct for CreateUploadCredentialsReq
type CreateUploadCredentialsReq struct {
	Channel string `json:"channel,omitempty"`
	Extra map[string]interface{} `json:"extra,omitempty"`
}
