/*
 * storage open api
 *
 * storage open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package storage
// QCloudCredentialsParams 腾讯云计算上传凭证参数
type QCloudCredentialsParams struct {
	// 存储桶所在区域，如：ap-guangzhou
	Region string `json:"region"`
	// 存储桶名称
	Bucket string `json:"bucket"`
}
